In [1]:
print("hello, subha nababarsa")

hello, subha nababarsa


In [1]:
print("oho uth ftu dft")

oho uth ftu dft


In [ ]:
import numpy as np

In [1]:
np.array([1,2,3,4])

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [5]:
arr= np.array([1,2,3,4])

In [4]:
arr=np.array
arr

<function numpy.array>

In [6]:
arr = np.array([1,2,3,4])

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
a=[5,4,3,2,1]
a

[5, 4, 3, 2, 1]

In [9]:
b = [7,8,9,4,"subhas"]
b

[7, 8, 9, 4, 'subhas']

In [10]:
np.array(b)

array(['7', '8', '9', '4', 'subhas'], dtype='<U21')

In [11]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [14]:
m = [1,11,2]

In [15]:
np.array(m)

array([ 1, 11,  2])

In [16]:
arr=np.zeros(6)

In [17]:
arr

array([0., 0., 0., 0., 0., 0.])

In [18]:
arr=np.zeros((4,16))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
arr= np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [20]:
arr = np.linspace(1,20,5)
arr

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [21]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
random generation function

In [22]:
np.random.rand(5)

array([0.26350674, 0.08417938, 0.50433146, 0.32882107, 0.34333417])

In [1]:
np.random.randn(10)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
np.random.randn(10)

array([ 0.252322  , -1.3801488 , -0.83403835, -0.63926756, -3.06996969,
       -1.47638625, -1.08106103,  0.46265623, -0.46556419,  0.09621219])

In [4]:
np.random.randint(10,20)

15

In [5]:
np.random.randint(10,20,10)

array([17, 14, 12, 10, 17, 14, 18, 14, 18, 16], dtype=int32)

In [ ]:
array attributes

In [7]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr.shape

(3, 3)

In [9]:
arr.size

9

In [10]:
arr.dtype

dtype('int64')

In [ ]:
array methods

In [12]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr.min()

np.int64(1)

In [15]:
arr.max()

np.int64(9)

In [16]:
arr.sum()

np.int64(45)

In [17]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [18]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [19]:
arr.mean()

np.float64(5.0)

In [20]:
arr.std()

np.float64(2.581988897471611)

In [22]:
arr.argmax()

np.int64(8)

In [23]:
arr.argmin()

np.int64(0)

In [25]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [26]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
numpy indexing and slicing of vectors

In [27]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [28]:
arr[0]

np.int64(11)

In [29]:
arr[9]

np.int64(20)

In [30]:
arr[1:4]

array([12, 13, 14])

In [31]:
arr[1:6:2]

array([12, 14, 16])

In [32]:
arr[1:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
numpy indexing and slicing of matrix

In [37]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [38]:
arr[0,0]

np.int64(1)

In [39]:
arr[3,2]

np.int64(18)

In [40]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [41]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
boolean indexing

In [43]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
array operatios

In [1]:
import numpy as np

In [ ]:
arithmetic operation

In [2]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a1+a2

array([ 7,  9, 11, 13, 15])

In [3]:
a2-a1

array([5, 5, 5, 5, 5])

In [4]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [5]:
a2/a1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [7]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1//a2

array([0, 0, 0, 0, 0])

In [9]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [ ]:
broadcasting

In [11]:
l=[15,25,35,45]
arr=np.array(l)
arr

array([15, 25, 35, 45])

In [12]:
arr+10

array([25, 35, 45, 55])

In [13]:
arr/10

array([1.5, 2.5, 3.5, 4.5])

In [16]:
arr2=np.arange(1,21).reshape(4,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

arr2+10

In [18]:
arr3=arr2+10
arr3

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [20]:
arr4=arr2[0:3,1:2]+10
arr4

array([[12],
       [17],
       [22]])

In [ ]:
deep and shallow copy

In [21]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
slice=a[:5]
slice

array([1, 2, 3, 4, 5])

In [23]:
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [24]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
matrix operation

In [29]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
mat1*mat2

array([[ 5, 12],
       [21, 32]])

In [30]:
mat1@mat2

array([[19, 22],
       [43, 50]])

In [31]:
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [ ]:
advance array manipulation
stacking array

In [32]:
mat1

array([[1, 2],
       [3, 4]])

In [33]:
mat2

array([[5, 6],
       [7, 8]])

In [35]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [36]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
splitting array

In [43]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [1]:
np.hsplit(c)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
np.hsplit(c,2)

NameError: name 'c' is not defined

In [4]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
a=np.split(c,2)
a

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [6]:
np.hsplit(c,3)

ValueError: array split does not result in an equal division

In [7]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [8]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [9]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [ ]:
//valid sudoku

In [14]:
import numpy as np

In [16]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [21]:
r=np.sum(s,axis=1)
if np.all(r==45):
    print("this sudoku is correct for rows")
else:
    print("a invalid sudoku")

this sudoku is correct for rows


In [24]:
c=np.sum(s,axis=0)
for i in c:
    if i!=45:
        print("this is a invalid sudoku")
        break
else:
    print("this sudoku is valid for columns also")

this sudoku is valid for columns also


In [26]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [ ]:
//general questions

In [27]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [28]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [30]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [32]:
#Find the average math marks of students.
np.mean(data[:,1])

np.float64(81.6)

In [38]:
#Extract Math marks of all students.
math_marks=data[:,1]
print(math_marks)

[85 92 76 65 90]


In [39]:
#Find the highest Science mark.
science_marks=data[:,2]
highest=np.max(science_marks)
print(highest)

95


In [44]:
#Get details of the student who scored more than 90 in Math.
import numpy as np

data = np.array([
    [18, 85, 78],
    [19, 92, 88],
    [17, 76, 95],
    [18, 65, 70],
    [20, 90, 85]
])

data[data[:,1] > 90]

array([[19, 92, 88]])

In [45]:
#Get details of the student who scored more than 90 in science.
data[data[:,2]>90]

array([[17, 76, 95]])

In [47]:
#Increase Math marks of all students by 5.
data_1=data[:,1]+5
print(data_1)

[90 97 81 70 95]


In [49]:
#Increase age of all students by 15.
age_in=data[:,0]+15
print(age_in)

[33 34 32 33 35]


In [53]:
#Find how many students are younger than 19.
#np.sum(data[:,0]<19)
int(np.sum(data[:,0] < 19))

3

In [56]:
#Calculate the average marks in each subject (column-wise mean).
avg=np.mean(data[:,1:],axis=0)
print(avg)

[81.6 83.2]


In [59]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [62]:
#Replace all Science marks < 75 with 0.
data[data[:, 2] < 75, 2] = 0
print(data)

[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65  0]
 [20 90 85]]
